### ISSUE TITLE
Rejudging solution

### ISSUE THREAD

**Issue by Keys9873** [shine00chang/argon#8]
It would be nice if we can rejudge the solutions from the admin panel (this way their time penalty doesn't change).

**Comment by shine00chang** [comment]
Added with a91087bd07491ab9a5fc8c30c5db09a52d893085
Something's up with submission TbIsUKb2wRzGh5kBLd9ha, wil check later

**Comment by shine00chang** [comment]
aakash might just be wrong XD.
closing
